# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
#use_frameworks!

target 'iOSBlogReader' do
    
#https://github.com/SnapKit/Masonry
pod 'Masonry', '~> 0.6'
#https://github.com/facebook/pop
pod 'pop', '~> 1.0'
#https://github.com/AFNetworking/AFNetworking
pod 'AFNetworking'
#https://github.com/HeshamMegid/HMSegmentedControl
pod 'HMSegmentedControl', '~> 1.5'
#https://github.com/ibireme/YYModel
pod 'YYModel', '~> 1.0'
#https://github.com/CocoaLumberjack/CocoaLumberjack
pod 'CocoaLumberjack', '~> 2.2'
#https://github.com/CoderMJLee/MJRefresh
pod 'MJRefresh', '~> 3.1'
#https://github.com/ibireme/YYWebImage
pod 'YYWebImage', '~> 1.0'

#https://github.com/dfmuir/KINWebBrowser
pod 'KINWebBrowser', '~> 1.3'

#https://github.com/mwaterfall/MWFeedParser
#pod 'MWFeedParser', '~> 1.0'

end

