# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'iOSBlogReader' do
pod 'Masonry', '~> 0.6'
pod 'MagicalRecord', '~> 2.3'
pod 'pop', '~> 1.0'
pod 'MWFeedParser', '~> 1.0'
pod 'AFNetworking', '~> 3.0'

end

