# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 00:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Angle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zindex', models.IntegerField(default=0, verbose_name='排序参考值')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='描述')),
                ('iconfont', models.CharField(blank=True, default='', max_length=20, verbose_name='IconFont')),
            ],
            options={
                'verbose_name': '视角',
                'ordering': ['zindex'],
                'verbose_name_plural': '视角',
            },
        ),
        migrations.CreateModel(
            name='Aspect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zindex', models.IntegerField(default=0, verbose_name='排序参考值')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='描述')),
                ('iconfont', models.CharField(blank=True, default='', max_length=20, verbose_name='IconFont')),
            ],
            options={
                'verbose_name': '二级分类',
                'ordering': ['zindex'],
                'verbose_name_plural': '二级分类',
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.TextField(max_length=1000, verbose_name='网址')),
                ('description', models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='描述')),
                ('favicon', models.TextField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, max_length=1000, null=True, upload_to='screenshots', verbose_name='截图')),
                ('feed_url', models.TextField(blank=True, max_length=1000, null=True)),
                ('feed_type', models.SmallIntegerField(default=0)),
                ('clicks', models.BigIntegerField(default=0, verbose_name='点击次数')),
                ('zindex', models.IntegerField(default=0, verbose_name='排序参考值')),
                ('region', models.IntegerField(default=0, verbose_name='区域')),
                ('content_type', models.IntegerField(default=0)),
                ('large_icon', models.ImageField(blank=True, null=True, upload_to='siteicons', verbose_name='图标')),
                ('angle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='x123.Angle', verbose_name='视角')),
                ('aspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='x123.Aspect', verbose_name='二级分类')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '网址',
                'verbose_name_plural': '网址',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zindex', models.IntegerField(default=0, verbose_name='排序参考值')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='描述')),
                ('iconfont', models.CharField(blank=True, default='', max_length=20, verbose_name='IconFont')),
            ],
            options={
                'verbose_name': '一级分类',
                'ordering': ['zindex'],
                'verbose_name_plural': '一级分类',
            },
        ),
        migrations.AddField(
            model_name='aspect',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='x123.Domain', verbose_name='一级分类'),
        ),
    ]
