# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x123', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='angle',
            name='tag',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tag'),
        ),
        migrations.AddField(
            model_name='aspect',
            name='tag',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tag'),
        ),
        migrations.AddField(
            model_name='domain',
            name='tag',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tag'),
        ),
    ]
