# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 01:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('x123', '0002_auto_20160222_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='angle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='x123.Angle', verbose_name='视角'),
        ),
    ]
