# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-06 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x123', '0003_auto_20160222_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='spider',
            field=models.TextField(blank=True, max_length=20, null=True, verbose_name='爬虫'),
        ),
    ]
