# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-06 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('x123', '0004_bookmark_spider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='spider',
            field=models.TextField(blank=True, default='', max_length=20, verbose_name='爬虫'),
        ),
    ]
